In [1]:
import sklearn.preprocessing as pp
import numpy as np
import pandas as pd

In [2]:
x = [[1,2,3],[2,4,6]]
y = [[1,3,np.nan],[2,6,8]]
z = [[1,2,3],[2,4,6],[3,6,9]]

In [15]:
mm = pp.MinMaxScaler()
ma = pp.MaxAbsScaler()
ss = pp.StandardScaler(with_std=False)

In [4]:
ss.fit_transform(x)

array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])

In [5]:
mm.fit_transform(z)

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [6]:
ma.fit_transform(z)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.66666667, 0.66666667],
       [1.        , 1.        , 1.        ]])

In [7]:
ss.fit_transform(z)

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [8]:
mm.fit_transform(y)

array([[ 0.,  0., nan],
       [ 1.,  1.,  0.]])

In [19]:
x1 = [[2,1,2],[4,2,4]]
mm.fit(x1)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [20]:
ss.fit(x1)

StandardScaler(copy=True, with_mean=True, with_std=False)

In [21]:
ss.transform(x1)

array([[-1. , -0.5, -1. ],
       [ 1. ,  0.5,  1. ]])